# Generated by Django 3.0 on 2021-08-31 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbconame', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.CharField(max_length=250)),
                ('crid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EApp.Courses')),
            ],
        ),
    ]
