# Generated by Django 3.0 on 2021-09-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cimage',
            field=models.ImageField(default='courses.jpeg', upload_to='Courses/'),
        ),
    ]
