# Generated by Django 3.0 on 2021-09-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pcimg',
            field=models.ImageField(default='profile.jpeg', upload_to='Profiles/'),
        ),
    ]
